/** Section metadata, independent columns, keyboard order and UE updates. No remote persistence claim. */
import fs from 'node:fs';import assert from 'node:assert/strict';import {createRequire}from'node:module';import{serve}from'../tools/serve.mjs';import{blockHTML}from'../tools/render-content.mjs';
const require=createRequire(import.meta.url),{chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');const server=await serve(4286),browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE,args:['--no-sandbox']}),page=await browser.newPage({viewport:{width:1280,height:900}});page.setDefaultTimeout(7000);const report={scope:'Local layout and simulated UE patches; no authenticated AEM persistence',tests:[]};let errors=[];page.on('pageerror',e=>errors.push(e.message));
async function test(name,fn){errors=[];try{await fn();assert.deepEqual(errors,[]);report.tests.push({name,pass:true});console.log('OK',name)}catch(e){report.tests.push({name,pass:false,error:e.message});console.log('FAIL',name,e.message)}}
const pages=JSON.parse(fs.readFileSync('content/pages.json'));const origin='http://127.0.0.1:4286';
async function visit(path='showcase/layouts'){await page.goto(origin+'/'+path);await page.waitForFunction(()=>document.documentElement.dataset.toranjaLoaded==='true')}
try{await visit();
for(const [cls,ratio]of [['columns-2',1],['columns-33-67',.5],['columns-67-33',2],['columns-25-75',1/3],['columns-75-25',3]])await test('Proporção desktop '+cls,async()=>{const dimensions=await page.locator('main .'+cls).first().locator(':scope > .layout-column').evaluateAll(ns=>ns.map(n=>n.getBoundingClientRect().width));assert.equal(dimensions.length,2);assert.ok(Math.abs(dimensions[0]/dimensions[1]-ratio)<.02);});
await test('Imagem, título e botão permanecem em componentes independentes',async()=>{const section=page.locator('main .columns-33-67');assert.equal(await section.locator('[data-column="2"] .block').count(),3);assert.equal(await section.locator('[data-column="1"] .ds-image').count(),1)});
await test('Card: conteúdo com margem interna e separação real entre título e texto',async()=>{const c=page.locator('main .columns-3 .ds-card-content').first();const style=await c.evaluate(n=>({padding:getComputedStyle(n).paddingTop,gap:getComputedStyle(n).gap,heading:n.querySelector('h3').getBoundingClientRect().bottom,body:n.querySelector('p').getBoundingClientRect().top}));assert.equal(style.padding,'24px');assert.equal(style.gap,'16px');assert.ok(style.body-style.heading>=15);});
await test('Metadados diretos do publicador são interpretados',async()=>{const r=await page.evaluate(async()=>{const{applySectionLayout}=await import('/scripts/layout.js');const s=document.createElement('div');s.className='section columns-2';s.setAttribute('data-layoutmode','columns');s.setAttribute('data-layoutgap','large');document.querySelector('main').append(s);applySectionLayout(s);const result=[s.dataset.layoutMode,s.dataset.layoutGap,getComputedStyle(s).getPropertyValue('--section-gap').trim()];s.remove();return result});assert.deepEqual(r,['columns','large','40px'])});
for(const [field,values]of [['layoutWidth',['reading','standard','wide','full']],['layoutGap',['compact','standard','large']],['layoutPadding',['none','compact','standard','large']],['layoutAlign',['start','center','end','stretch']],['layoutBackground',['page','neutral','brand']]])await test('Controle '+field,async()=>{const valuesFound=await page.evaluate(async({field,values})=>{const{applySectionLayout}=await import('/scripts/layout.js');const s=document.querySelector('main .columns-2');return values.map(v=>{s.dataset[field]=v;applySectionLayout(s);const css=getComputedStyle(s);return{value:s.dataset[field],width:css.maxWidth,gap:css.gap,padding:css.paddingTop,align:css.alignItems,background:css.backgroundColor}})},{field,values});assert.deepEqual(valuesFound.map(x=>x.value),values);assert.ok(new Set(valuesFound.map(x=>JSON.stringify({...x,value:null}))).size>1)});
await test('Mobile: uma coluna e ordem de leitura invertida no DOM',async()=>{await page.setViewportSize({width:390,height:900});await page.waitForTimeout(100);const s=page.locator('#mobile-reverse');assert.equal(await s.locator(':scope > .layout-column').first().getAttribute('data-column'),'2');assert.equal((await s.evaluate(n=>getComputedStyle(n).gridTemplateColumns)).split(' ').length,1);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false)});
await test('Retorno ao desktop restaura a ordem',async()=>{await page.setViewportSize({width:1280,height:900});await page.waitForTimeout(100);assert.equal(await page.locator('#mobile-reverse > .layout-column').first().getAttribute('data-column'),'1')});
await test('UE: mudar coluna do componente mantém recurso e destino',async()=>{await visit();const b=structuredClone(pages['showcase/layouts'].sections[1].content.find(b=>b.block==='ds-button'));b.properties.classes_layoutColumn='col-1';await page.evaluate(async markup=>{const m=document.querySelector('main');m.dataset.aueResource='urn:layout:main';m.innerHTML='<div class="columns-2" data-layout-mode="columns" data-aue-resource="urn:layout:section" data-aue-type="container" data-aue-model="section" data-aue-filter="section">'+markup+'</div>';const a=await import('/scripts/aem.js');a.decorateSections(m);a.decorateBlocks(m);await a.loadSections(m);await import('/scripts/editor-support.js');},blockHTML(b,true,'urn:layout:button'));assert.equal(await page.locator('[data-column="1"] [data-aue-resource="urn:layout:button"].block').count(),1);b.properties.classes_layoutColumn='col-2';await page.evaluate(markup=>document.querySelector('main').dispatchEvent(new CustomEvent('aue:content-patch',{bubbles:true,detail:{request:{target:{resource:'urn:layout:button'}},response:{updates:[{content:markup}]}}})),blockHTML(b,true,'urn:layout:button'));await page.locator('[data-column="2"] [data-aue-resource="urn:layout:button"].block').waitFor();assert.equal(await page.locator('[data-aue-resource="urn:layout:section"]').getAttribute('data-aue-filter'),'section')});
await test('UE: mudar layout da seção redesenha os componentes',async()=>{const b=structuredClone(pages['showcase/layouts'].sections[1].content.find(b=>b.block==='ds-button'));const markup='<div class="columns-3" data-layout-mode="columns" data-layout-gap="large" data-aue-resource="urn:layout:section" data-aue-type="container" data-aue-model="section" data-aue-filter="section">'+blockHTML(b,true,'urn:layout:button')+'</div>';await page.evaluate(markup=>document.querySelector('main').dispatchEvent(new CustomEvent('aue:content-patch',{bubbles:true,detail:{request:{target:{resource:'urn:layout:section'}},response:{updates:[{content:markup}]}}})),markup);await page.locator('.section.columns-3[data-section-status=loaded]').waitFor();assert.equal(await page.locator('.layout-column').count(),3);assert.equal(await page.locator('[data-aue-resource="urn:layout:button"].block').count(),1)});
for(const [slug,id]of [['formulario','v3-form'],['busca','v3-search'],['video','v3-video'],['simulador','v3-simulator']])await test('Layout independente Custom '+id,async()=>{await visit('showcase/custom/'+slug);const b=structuredClone(pages['showcase/custom/'+slug].sections.flatMap(s=>s.content).find(b=>b.block===id));b.properties.classes_layoutColumn='col-2';await page.evaluate(async markup=>{const main=document.querySelector('main');main.innerHTML='<div class="columns-2" data-layout-mode="columns">'+markup+'</div>';const a=await import('/scripts/aem.js');a.decorateSections(main);a.decorateBlocks(main);await a.loadSections(main);},blockHTML(b,true,'urn:custom:'+id));assert.equal(await page.locator('[data-column="2"] .'+id+'[data-toranja-ready="true"]').count(),1);assert.equal(await page.locator('[data-column="1"] .block').count(),0)});
for(const width of [1280,390]){await page.setViewportSize({width,height:900});for(const route of ['','showcase/layouts','showcase/v3/formulario','composicoes','demo-toranja','showcase/custom','showcase/custom/formulario','showcase/custom/busca','showcase/custom/video','showcase/custom/simulador']){await visit(route);await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'docs/final-'+(route.replaceAll('/','-')||'home')+'-'+width+'.png',fullPage:true});}}
}finally{fs.writeFileSync('docs/layout-'+(process.env.QA_ROUND||'development')+'.json',JSON.stringify(report,null,2));await browser.close();await new Promise(r=>server.close(r));}process.exitCode=report.tests.some(t=>!t.pass)?1:0;
