import fs from 'node:fs';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {serve} from '../tools/serve.mjs';import {blockHTML} from '../tools/render-content.mjs';
const require=createRequire(import.meta.url),{chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');const server=await serve(4284),browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:Number(process.env.QA_WIDTH)||1280,height:900}});page.setDefaultTimeout(5000);const report={scope:'Conteúdo local, novas instâncias, temas e mídia; sem AEM remoto.',tests:[]};let errors=[];page.on('pageerror',e=>errors.push(e.message));
async function test(name,fn){errors=[];try{await fn();assert.deepEqual(errors,[]);report.tests.push({name,pass:true});console.log('OK',name)}catch(e){report.tests.push({name,pass:false,error:e.message,errors});console.log('FAIL',name,e.message)}}
const definitions=JSON.parse(fs.readFileSync('component-definition.json')).groups.flatMap(g=>g.components).filter(d=>d.id.startsWith('ds-')&&!d.plugins.xwalk.page.resourceType.endsWith('/item'));
try{
await page.goto('http://127.0.0.1:4284/');await page.waitForFunction(()=>document.documentElement.dataset.toranjaLoaded);
for(const d of definitions)await test('Nova instância '+d.id,async()=>{const props={...d.plugins.xwalk.page.template};for(const key of ['name','model','filter'])delete props[key];const markup=blockHTML({block:d.id,properties:props,items:[]},true,'urn:new:'+d.id);const result=await page.evaluate(async({id,markup})=>{const main=document.querySelector('main');main.dataset.aueResource='urn:main';main.innerHTML=markup;const block=main.firstElementChild;block.classList.add('block');await(await import('/blocks/'+id+'/'+id+'.js')).default(block);await new Promise(r=>setTimeout(r,50));return block.dataset.dsError||null},{id:d.id,markup});assert.equal(result,null)});
for(const d of JSON.parse(fs.readFileSync('component-definition.json')).groups.find(g=>g.id==='toranja-custom').components)await test('Nova instância Custom '+d.id,async()=>{const props={...d.plugins.xwalk.page.template};for(const key of ['name','model','filter'])delete props[key];const markup=blockHTML({block:d.id,properties:props,items:[]},true,'urn:new:'+d.id);await page.evaluate(async({id,markup})=>{const main=document.querySelector('main');main.dataset.aueResource='urn:main';main.innerHTML=markup;const block=main.firstElementChild;block.classList.add('block');await(await import('/blocks/'+id+'/'+id+'.js')).default(block);},{id:d.id,markup});assert.equal(await page.locator('.'+d.id).getAttribute('data-toranja-ready'),'true')});
for(const path of ['formulario','controles','composicao','dados','acoes','video'])await test('Showcase V3 '+path,async()=>{await page.goto('http://127.0.0.1:4284/showcase/v3/'+path);await page.waitForFunction(()=>document.documentElement.dataset.toranjaLoaded);await page.waitForTimeout(100);const errors=await page.locator('[data-ds-error]').evaluateAll(nodes=>nodes.map(e=>e.dataset.dsError));assert.deepEqual(errors,[]);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);if(path==='composicao')assert.ok(await page.getByText('Conta digital',{exact:true}).count());});
await test('Ação de botão abre o painel configurado',async()=>{await page.goto('http://127.0.0.1:4284/showcase/v3/acoes');await page.getByRole('button',{name:'Abrir detalhes',exact:true}).click();await page.getByText('Este painel foi aberto por uma ação configurável.').waitFor({state:'visible'});await page.keyboard.press('Escape');await page.getByText('Este painel foi aberto por uma ação configurável.').waitFor({state:'hidden'})});
await test('Vídeo local: mídia carregada e legendas presentes',async()=>{await page.goto('http://127.0.0.1:4284/showcase/custom/video');await page.getByRole('button',{name:/Assistir/}).click();await page.waitForFunction(()=>document.querySelector('video')?.readyState>=1);const r=await page.locator('video').evaluate(v=>({width:v.videoWidth,tracks:v.querySelectorAll('track').length,ratio:getComputedStyle(v.parentElement).aspectRatio}));assert.equal(r.width,960);assert.equal(r.tracks,1);assert.equal(r.ratio,'16 / 9')});
for(const theme of ['pf-light','pf-dark','pj-light','pj-dark'])await test('Tema '+theme,async()=>{await page.goto('http://127.0.0.1:4284/showcase/v3/controles');await page.waitForFunction(()=>document.documentElement.dataset.toranjaLoaded);const actual=await page.evaluate(theme=>{document.documentElement.setAttribute('toranja-theme',theme);const s=getComputedStyle(document.documentElement);return {accent:s.getPropertyValue('--theme-accent').trim(),official:s.getPropertyValue('--color-background-brand-default').trim(),background:s.getPropertyValue('--theme-bg').trim(),surface:s.getPropertyValue('--color-background-neutral-default').trim()}},theme);assert.equal(actual.accent,actual.official);assert.equal(actual.background,actual.surface);assert.ok(actual.official);});
await page.goto('http://127.0.0.1:4284/showcase/v3/composicao');await page.waitForFunction(()=>document.documentElement.dataset.toranjaLoaded);await page.screenshot({path:'docs/v3-composition-'+(process.env.QA_WIDTH||'1280')+'.png',fullPage:true});
}finally{fs.writeFileSync('docs/v3-content-'+(process.env.QA_ROUND||'development')+'.json',JSON.stringify(report,null,2));await browser.close();await new Promise(r=>server.close(r));}
process.exitCode=report.tests.some(t=>!t.pass)?1:0;
