/** Critérios V3: contratos e comportamento real no navegador; sem serviços externos. */
import fs from 'node:fs';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {serve} from '../tools/serve.mjs';import {blockHTML} from '../tools/render-content.mjs';
const require=createRequire(import.meta.url);const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');const server=await serve(4283);const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:Number(process.env.QA_WIDTH)||1280,height:900}});page.setDefaultTimeout(4000);
const report={scope:'Runtime local compilado + serialização XWalk simulada. Sem sessão AEM autenticada.',tests:[]};let errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
const schemas=JSON.parse(fs.readFileSync('scripts/ds-schema.json'));
async function test(name,fn){errors=[];try{await fn();assert.deepEqual(errors,[]);report.tests.push({name,pass:true});console.log('OK',name)}catch(e){report.tests.push({name,pass:false,error:e.message,errors});console.log('FAIL',name,e.message)}}
await page.goto('http://127.0.0.1:4283/scripts/ds-schema.json');await page.evaluate(async()=>{document.body.innerHTML='<main></main>';window.schemas=await(await fetch('/scripts/ds-schema.json')).json();window.runtime=await import('/scripts/ds-runtime/toranja-runtime.js');const l=document.createElement('link');l.rel='stylesheet';l.href='/scripts/ds-runtime/toranja-runtime.css';document.head.append(l);document.documentElement.setAttribute('toranja-theme','pf-light');window.events=[];document.addEventListener('toranja:interaction',e=>events.push(e.detail));});
async function mount(id,props){await page.evaluate(({id,props})=>{window.dispose?.();const block=document.createElement('div');block.className=id+' block';const host=document.createElement('div');host.id='test-control';host.className='ds-official';block.append(host);document.querySelector('main').replaceChildren(block);window.events=[];window.dispose=runtime.mount(host,schemas[id],props,{resolveLink:x=>x,editing:true});},{id,props});await page.waitForTimeout(80);}
try{
await test('F01/F05 ListItem: checkbox escolhido, valor e callback',async()=>{await mount('ds-list-item',{label:'Preferência',leadingCheckbox:{checked:true,state:'enabled'},state:'enabled'});assert.equal(await page.getByRole('checkbox').count(),1);assert.equal(await page.locator('.avatar').count(),0);assert.equal(await page.getByRole('checkbox').getAttribute('aria-checked'),'true');await page.getByRole('checkbox').click();assert.equal(await page.getByRole('checkbox').getAttribute('aria-checked'),'false');assert.ok(await page.evaluate(()=>events.some(e=>e.event==='leadingCheckbox.onChange'&&e.args[0]===false)))});
await test('F01 ListItem: radio escolhido sem botão fantasma',async()=>{await mount('ds-list-item',{label:'Opção',trailingRadioButton:{checked:false,id:'radio',name:'g',value:'a',state:'enabled'}});assert.equal(await page.locator('input[type=radio]').count(),1);assert.equal(await page.locator('button').count(),0);await page.locator('input').check();assert.equal(await page.locator('input').isChecked(),true)});
await test('F05 ListItemControl Stepper: value=5, incremento=6 e evento',async()=>{await mount('ds-list-item-control',{label:'Quantidade',trailingVariant:'stepper',trailingProps:{value:5,min:0,max:10,step:1}});assert.equal(await page.locator('input').inputValue(),'5');await page.getByRole('button',{name:'Aumentar',exact:true}).click();assert.equal(await page.locator('input').inputValue(),'6');assert.ok(await page.evaluate(()=>events.some(e=>e.event==='trailingProps.onStepperChange'&&e.args[0]===6)))});
await test('F03 Tagging preserva contrato e elimina texto pessoal',async()=>{await mount('ds-button',{label:'Nome privado',state:'enabled'});await page.locator('button').click();const tag=await page.evaluate(()=>events.find(e=>e.event==='onTag')?.args[0]);assert.equal(tag.ComponentProperties.component_name,'Button');assert.ok(tag.name);assert.ok(!JSON.stringify(tag).includes('Nome privado'))});
await test('F04 TextArea emite novo valor',async()=>{await mount('ds-text-area',{label:'Mensagem',value:'Inicial',state:'enabled'});await page.locator('textarea').fill('Editado');assert.ok(await page.evaluate(()=>events.some(e=>e.event==='onChange'&&e.args[0]==='Editado')))});
await test('F10 Select: setas, seleção zero e Escape',async()=>{await mount('ds-select',{label:'Escolha',state:'enabled',$options:[{label:'Zero',value:0},{label:'Um',value:1}]});const combo=page.getByRole('combobox');await combo.click();await combo.press('Escape');assert.equal(await page.getByRole('listbox').count(),0);await combo.press('Enter');await combo.press('Home');await combo.press('Enter');assert.ok(await page.evaluate(()=>events.some(e=>e.event==='onChange'&&e.args[0]===0)))});
await test('F10 Select disabled não abre',async()=>{await mount('ds-select',{label:'Escolha',state:'disabled',$options:['A']});await page.locator('.ds-select .ds-select').click();assert.equal(await page.getByRole('listbox').count(),0)});
await test('F02 Ações independentes e bloqueio em autoria',async()=>{const result=await page.evaluate(async()=>{const {runAction,registerAction}=await import('/scripts/actions.js');let seen=[];registerAction('one',()=>seen.push(1));registerAction('two',()=>seen.push(2));runAction({kind:'custom',id:'one'},document.body,false);runAction({kind:'custom',id:'two'},document.body,false);runAction({kind:'custom',id:'one'},document.body,true);return seen});assert.deepEqual(result,[1,2])});
await test('F11 Painel abre por identificador e fecha com Escape',async()=>{await mount('ds-bottom-sheet',{title:'Painel',slot:'<p>Conteúdo do painel</p>',isOpen:false,overlay:'on',position:'hug',$overlayId:'painel'});await page.evaluate(()=>document.dispatchEvent(new CustomEvent('toranja:overlay',{detail:{id:'painel',open:true}})));await page.getByText('Conteúdo do painel').waitFor({state:'visible'});await page.keyboard.press('Escape');await page.getByText('Conteúdo do painel').waitFor({state:'hidden'})});
await test('F11 FAB flutuante e inline',async()=>{await mount('ds-floating-action-button',{label:'Ação',icon:'ic_add',state:'enabled',$placement:'floating'});assert.equal(await page.locator('.btn-fab').evaluate(e=>getComputedStyle(e).position),'fixed');await mount('ds-floating-action-button',{label:'Ação',icon:'ic_add',state:'enabled',$placement:'inline'});assert.equal(await page.locator('.btn-fab').evaluate(e=>getComputedStyle(e).position),'relative')});
await test('F06 Tipos: hints com limite e validação de séries',async()=>{const result=await page.evaluate(async()=>{const {normalizeProps}=await import('/scripts/ds-values.js');let errors=0;try{normalizeProps({hints:['1','2','3','4']},schemas['ds-input-text'])}catch{errors++}try{normalizeProps({values:[1,2],categories:['A']},schemas['ds-chart-bar'])}catch{errors++}return errors});assert.equal(result,2)});
await test('F07 Listas editoriais substituem JSON sem perdas',async()=>{const s=schemas['ds-select'],c=s.collections.find(c=>c.id==='$options'),label=c.descriptors.find(d=>d.name==='label').key,value=c.descriptors.find(d=>d.name==='value').key;const b={block:'ds-select',properties:{schemaVersion:'toranja-v3',p6c6162656c:'Lista'},items:[{collection:'$options',[label]:'Opção do autor',[value]:'a'}]};await page.evaluate(async markup=>{window.dispose?.();document.querySelector('main').innerHTML=markup;await(await import('/blocks/ds-select/ds-select.js')).default(document.querySelector('.ds-select'));},blockHTML(b));await page.getByRole('combobox').click();assert.equal(await page.getByRole('option').innerText(),'Opção do autor')});
await test('F08 Composição Card com imagem, texto e CTA',async()=>{await mount('ds-card',{state:'enabled',children:{$compositionGroup:[{$composition:true,kind:'card',title:'Plano',body:'<p>Detalhes</p>',href:'/planos',label:'Conhecer'}]}});assert.equal(await page.getByRole('link',{name:'Conhecer'}).getAttribute('href'),'/planos');assert.equal(await page.getByText('Detalhes').count(),1)});
await test('F12 Contrato de integração e timeout sem rede',async()=>{const values=await page.evaluate(async()=>{const {registerIntegration,runIntegration}=await import('/scripts/integrations.js');registerIntegration('fixture',async p=>({received:p.name}));const r=await runIntegration('fixture',{name:'Teste'});registerIntegration('slow',()=>new Promise(()=>{}));let timeout=false;try{await runIntegration('slow',{}, {timeout:10})}catch(e){timeout=e.name==='AbortError'}return [r.received,timeout]});assert.deepEqual(values,['Teste',true])});
await test('F12 Busca no corpo, acentos e exclusões',async()=>{const paths=await page.evaluate(async()=>{const {searchRecords}=await import('/scripts/search-index.js');return searchRecords([{path:'/produtos/credito',title:'Produto',body:'Crédito imobiliário'},{path:'/nav',title:'Crédito'},{path:'/privado',title:'Crédito',robots:'noindex'}],'credito').map(x=>x.path)});assert.deepEqual(paths,['/produtos/credito'])});
await test('F04 Form DS configurável, condição, payload e sucesso',async()=>{await page.evaluate(async()=>{window.dispose?.();document.querySelector('main').innerHTML='<div id="form-host"></div>';const {registerIntegration}=await import('/scripts/integrations.js');registerIntegration('formtest',async payload=>{window.payload=payload;return {ok:true}});window.dispose=runtime.mountForm(document.getElementById('form-host'),{id:'formtest',integrationId:'formtest',title:'Formulário',submitLabel:'Enviar teste',successMessage:'Recebido',fields:[{fieldName:'email',label:'Email',kind:'email',required:true},{fieldName:'extra',label:'Complemento',kind:'text',showWhenField:'email',showWhenValue:'teste@example.com'}]});});await page.getByLabel('Email',{exact:true}).fill('teste@example.com');await page.getByLabel('Complemento',{exact:true}).fill('Autor');await page.getByRole('button',{name:'Enviar teste'}).click();await page.getByText('Recebido',{exact:true}).waitFor();assert.deepEqual(await page.evaluate(()=>payload),{email:'teste@example.com',extra:'Autor'})});
await test('F12 Fonte dinâmica entrega dados e informa falha',async()=>{await page.evaluate(async()=>{const {registerIntegration}=await import('/scripts/integrations.js');registerIntegration('chart-fixture',async()=>({categories:['Teste'],values:[42]}));registerIntegration('chart-error',async()=>{throw Error('Falha controlada')})});await mount('ds-chart-bar',{$dataSource:'chart-fixture'});assert.equal(await page.locator('[data-ds-error]').count(),0);assert.ok(await page.getByText('Teste',{exact:true}).count());await mount('ds-chart-bar',{$dataSource:'chart-error'});assert.equal(await page.getByRole('alert').innerText(),'Falha controlada')});
await test('F06 Datas inválidas rejeitadas e data inicial única renderizada',async()=>{const r=await page.evaluate(async()=>{const {normalizeProps}=await import('/scripts/ds-values.js');try{normalizeProps({$defaultDate:'2026-02-30'},schemas['ds-date-picker']);return false}catch{return true}});assert.ok(r);await mount('ds-date-picker',{selectionMode:'single',$defaultDate:'2026-10-05',visibleMonth:'2026-10-01'});assert.equal(await page.locator('[data-ds-error]').count(),0)});
await test('F04 Form valida CPF e informa ausência/falha de integração',async()=>{await page.evaluate(()=>{window.dispose?.();document.querySelector('main').innerHTML='<div id="form-host"></div>';window.dispose=runtime.mountForm(document.getElementById('form-host'),{id:'cpf-test',submitLabel:'Validar',fields:[{fieldName:'cpf',label:'CPF',kind:'cpf',required:true}]})});await page.getByLabel('CPF',{exact:true}).fill('11111111111');await page.getByRole('button',{name:'Validar'}).click();await page.getByText('Informe um CPF válido.').waitFor();await page.getByLabel('CPF',{exact:true}).fill('52998224725');await page.getByRole('button',{name:'Validar'}).click();await page.getByText('Formulário preparado: integração de envio ainda não configurada.').waitFor();await page.evaluate(async()=>{window.dispose();const {registerIntegration}=await import('/scripts/integrations.js');registerIntegration('failed-form',async()=>{throw Error('Indisponível')});window.dispose=runtime.mountForm(document.getElementById('form-host'),{id:'fail',integrationId:'failed-form',failureMessage:'Tente depois',fields:[],submitLabel:'Enviar falha'})});await page.getByRole('button',{name:'Enviar falha'}).click();await page.getByText('Tente depois',{exact:true}).waitFor()});
await test('F13 Rotas com raiz configurada e home',async()=>{const r=await page.evaluate(async()=>{const {resolveLink}=await import('/scripts/links.js');return [resolveLink('/content/toranja-inter-demo/index.html',false),resolveLink('/carreiras',true)]});assert.deepEqual(r,['/','/content/toranja-inter-demo/carreiras.html'])});
await test('Tema oficial carregado',async()=>{await page.goto('http://127.0.0.1:4283/');await page.waitForFunction(()=>document.documentElement.dataset.toranjaLoaded);const values=await page.evaluate(()=>({brand:getComputedStyle(document.documentElement).getPropertyValue('--color-background-brand-default').trim(),accent:getComputedStyle(document.documentElement).getPropertyValue('--theme-accent').trim()}));assert.equal(values.brand,values.accent);assert.ok(values.brand)});
await test('Layout mobile sem overflow horizontal',async()=>{await page.setViewportSize({width:390,height:850});await page.waitForTimeout(100);const overflow=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth+1,nodes:[...document.querySelectorAll('main *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1).slice(0,12).map(e=>({tag:e.tagName,cls:e.className,right:e.getBoundingClientRect().right}))}));assert.equal(overflow.overflow,false,JSON.stringify(overflow.nodes))});
}finally{fs.writeFileSync('docs/v3-'+(process.env.QA_ROUND||'development')+'.json',JSON.stringify(report,null,2));await browser.close();await new Promise(r=>server.close(r));}
process.exitCode=report.tests.some(t=>!t.pass)?1:0;
