/** Editorial navigation for the official catalogue; preserves all individual examples. */
import fs from'node:fs';import{card,action}from'./content-api.mjs';
const pages=JSON.parse(fs.readFileSync('content/pages.json')),contract=JSON.parse(fs.readFileSync('docs/toranja-contract.json'));
const categories=[['Atoms','atomos','Átomos','Elementos essenciais para construir a interface.'],['Molecules','moleculas','Moléculas','Combinações que resolvem interações e apresentações de conteúdo.'],['Templates','templates','Templates','Estruturas de apresentação disponibilizadas pelo pacote oficial.']];
const examples=pages['demo-toranja'].sections.filter(s=>s.id?.startsWith('ds-'));
pages['demo-toranja'].sections=[{id:'catalogo',layoutPadding:'large',content:[{text:'<p>TORANJA / CATÁLOGO OFICIAL</p><h1>Um sistema para criar possibilidades.</h1><p>Explore os 64 componentes do Toranja. Os exemplos preservam o pacote oficial e expõem suas propriedades para autoria.</p>'},action('Ver layouts','/showcase/layouts')]},{style:'columns-3',layoutPadding:'compact',layoutAlign:'stretch',content:categories.map(([type,id,name,description])=>card(`<h3>${name}</h3><p>${contract.components.filter(c=>c.source.split('/')[1]===type).length} componentes</p><p>${description}</p><p><a href="#${id}">Explorar ${name.toLowerCase()} →</a></p>`))}];
for(const[type,id,name,description]of categories){pages['demo-toranja'].sections.push({id,layoutPadding:'large',layoutBackground:'brand',content:[{text:`<h2>${name}</h2><p>${description}</p>`}]});for(const c of contract.components.filter(c=>c.source.split('/')[1]===type)){const section=examples.find(s=>s.id===c.block);if(section){section.layoutPadding='standard';section.layoutWidth='reading';if(c.block==='ds-floating-action-button')section.content.find(b=>b.block===c.block).properties.placement='inline';pages['demo-toranja'].sections.push(section)}}}
if(!pages.composicoes.sections.some(s=>s.id==='intro-composicoes'))pages.composicoes.sections.unshift({id:'intro-composicoes',layoutPadding:'large',content:[{text:'<p>TORANJA / COMPOSIÇÕES</p><h1>Do componente à experiência.</h1><p>Exemplos de organização com imagem, conteúdo, controles e ações. Todos os blocos pertencem ao catálogo oficial; a seção define como eles se combinam.</p>'},action('Explorar layouts','/showcase/layouts')]});
for(const s of pages.composicoes.sections)for(const b of s.content){if(b.block==='ds-link'&&b.properties.p6c6162656c==='Simulador')b.properties.p6c6162656c='Valor monetário';}
fs.writeFileSync('content/pages.json',JSON.stringify(pages,null,2));
