"""Generate delivery evidence only from passing current test results."""
from pathlib import Path
import json,html,hashlib
r=Path(__file__).resolve().parents[1];d=r/'docs';rows=[];records=[]
for n in [1,2]:
 for prefix,label in [('baseline','119 páginas e catálogo'),('validation','64 componentes oficiais'),('acceptance','Interações e autoria simulada'),('v3','Contratos e integrações dos componentes'),('v3-content','Novas instâncias, temas e exemplos'),('layout','Layouts e edição de colunas'),('input-date-anchor','Calendário e formatos de datas'),('typography','Fontes efetivamente renderizadas')]:
  path=d/f'{prefix}-baseline-final-{n}.json';tests=json.loads(path.read_text())['tests'];passed=sum(bool(t['pass'])for t in tests)
  if passed!=len(tests):raise RuntimeError(f'Testes reprovados em {path.name}')
  records.append({'round':n,'suite':label,'passed':passed,'total':len(tests),'evidence':path.name});rows.append(f'<tr><td>{n}</td><td>{label}</td><td>{passed}/{len(tests)}</td><td><a href="{path.name}">JSON</a></td></tr>')
for file,key in [('baseline-package-validation.json','tests'),('package-audit.json','checks')]:
 if not all(x['pass']for x in json.loads((d/file).read_text())[key]):raise RuntimeError('Falha: '+file)
models=json.loads((r/'component-models.json').read_text());pages=json.loads((r/'content/pages.json').read_text());total=sum(x['total']for x in records);package=r/'content/toranja-inter-demo-content.zip';sha=hashlib.sha256(package.read_bytes()).hexdigest()
summary={'version':json.loads((r/'package.json').read_text())['version'],'reference':'@interco/inter-toranja 1.13.3','officialComponents':64,'customCatalogBlocks':4,'classifiedOwnProperties':751,'models':len(models),'modelFields':sum(len(m['fields'])for m in models),'pages':len(pages),'assets':11,'browserChecks':total,'rounds':records,'contentPackageSHA256':sha,'remoteAEMInstallationTested':False,'remoteUEPersistenceTested':False};(d/'final-summary.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2))
body=f'''<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Toranja EDS — entrega final V3</title><style>
*{{box-sizing:border-box}}body{{margin:0;font:16px/1.6 system-ui,sans-serif;background:#f6f5f2;color:#242220}}main{{max-width:1120px;margin:auto;padding:48px 24px}}header{{border-top:8px solid #ff7a00;padding-top:24px}}h1{{font-size:clamp(34px,6vw,64px);line-height:1.05;letter-spacing:-2px;margin:20px 0}}h2{{font-size:28px;font-weight:500}}.eyebrow{{font-size:12px;letter-spacing:2px;font-weight:700}}.metrics{{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin:32px 0}}.metric,section{{background:white;border:1px solid #dedbd4;border-radius:16px;padding:24px}}.metric strong{{display:block;font-size:34px}}section{{margin:20px 0}}a{{color:#a84a00}}table{{width:100%;border-collapse:collapse}}td,th{{padding:12px 8px;text-align:left;border-bottom:1px solid #ddd}}.table{{overflow:auto}}.note{{padding:20px;border-left:4px solid #ff7a00;background:#fff3e6}}.previews{{display:grid;grid-template-columns:2fr 1fr;gap:20px}}.previews img{{width:100%;height:auto;border:1px solid #ddd;border-radius:12px}}code{{font-size:13px;overflow-wrap:anywhere}}@media(max-width:700px){{main{{padding:24px 16px}}.metrics{{grid-template-columns:1fr 1fr}}.previews{{grid-template-columns:1fr}}section{{padding:18px}}}}
</style><main><header><div class="eyebrow">TORANJA / EDGE DELIVERY SERVICES</div><h1>O DS oficial.<br>Liberdade para compor.</h1><p>V3 final · versão técnica 3.1.1 · referência Toranja 1.13.3</p></header><div class="metrics"><div class="metric"><strong>64/64</strong>componentes oficiais</div><div class="metric"><strong>4</strong>blocos DS Toranja Custom</div><div class="metric"><strong>119</strong>páginas importáveis</div><div class="metric"><strong>{total}</strong>verificações de navegador</div></div><p class="note">Resultados locais em Chromium. A instalação FileVault, a publicação e a persistência autenticada no Universal Editor da instância não foram executadas. Cobertura 64/64 não significa todas as combinações de propriedades testadas.</p>
<section><h2>Escopo do catálogo</h2><p>64 exports públicos do snapshot, com 751 propriedades próprias classificadas. A organização segue os diretórios oficiais: 23 Átomos, 39 Moléculas e 2 Templates. Seção, texto padrão e tipos de item são infraestrutura de autoria XWalk.</p><p>Formulário, busca, vídeo e simulador estão restaurados em DS Toranja Custom, separados do catálogo oficial. O formulário aguarda integração de envio; a busca usa o índice público EDS; o player aceita arquivos e YouTube; o simulador usa taxas editoriais. Galeria: /showcase/custom. As fontes de dados e ações registráveis continuam preparadas.</p><p><a href="property-mapping.json">Mapeamento</a> · <a href="cobertura-propriedades.csv">Inventário</a> · <a href="vendor-integrity.json">Integridade do pacote oficial</a></p></section>
<section><h2>Layouts como propriedades de seção</h2><p>Colunas iguais e proporções 33/67, 67/33, 25/75 e 75/25. Grade automática ou colunas independentes, com vários componentes por coluna. Controles de largura, espaçamento, alinhamento, fundo e ordem no mobile. O agrupamento é visual; a estrutura AEM continua seção → blocos.</p><p>As colunas podem ser invertidas no mobile também na ordem do DOM. Atualizações de componente e de seção reaplicam o layout sem perder o recurso de autoria.</p><p><a href="AUTORIA-LAYOUTS.md">Guia de autoria</a> · Página de exemplo: <code>/showcase/layouts</code>.</p></section>
<section><h2>Revisão visual</h2><p>Home com hierarquia mais clara, imagem e texto em colunas, ações agrupadas e espaços consistentes. Catálogo com navegação por categorias; introdução para composições; exemplos individuais e de controles com largura de leitura e adaptação mobile.</p><div class="previews"><img src="preview-home-desktop.png" alt="Home desktop validada localmente"><img src="preview-home-mobile.png" alt="Home mobile validada localmente"></div></section>
<section><h2>Duas rodadas finais</h2><div class="table"><table><thead><tr><th>Rodada</th><th>Escopo</th><th>Aprovados</th><th>Evidência</th></tr></thead><tbody>{''.join(rows)}</tbody></table></div><p>As páginas e os componentes são exercitados em 1280px e 390px. A suíte de aceitação usa 900px. A suíte de layouts mede proporções a 1280px e alterna para 390px para verificar leitura, empilhamento e retorno ao desktop.</p><p>Também passaram nove gates de empacotamento e seis verificações do filtro de conteúdo e das ferramentas de sincronização. Foram conferidas proporções, controles de layout e atualizações simuladas no editor.</p><p><a href="package-audit.json">Gates do pacote</a> · <a href="baseline-package-validation.json">Escopo da substituição e ferramentas</a></p></section>
<section><h2>Instalação</h2><p>Sincronize o clone usando o utilitário incluído, revise as exclusões e faça commit/push. Faça backup do conteúdo AEM e importe o ZIP interno <code>content/toranja-inter-demo-content.zip</code>. Ele substitui os descendentes de <code>/content/toranja-inter-demo</code>, preservando <code>jcr:content</code> da raiz e sem filtros para <code>/conf</code>.</p><p>Publique páginas, nav, footer e referências. Confira salvar/reabrir os layouts no Author e a entrega em Preview/Live. Não é necessário recriar o site.</p><p><a href="DEPLOY-V3-FINAL.md">Deployment e reimportação</a> · <a href="INTEGRACOES-V3.md">Escopo das integrações</a></p><p>SHA-256 do pacote de conteúdo:<br><code>{sha}</code></p></section></main></html>'''
(d/'AUDITORIA-V3-FINAL.html').write_text(body);print('Auditoria final:',total,'verificações aprovadas.')
